# Pandas Basics

Pandas is a powerful Python library used for data analysis and manipulation. It works well with structured data like tables and spreadsheets.

To install:
```bash
pip install pandas
```

## Importing Pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in /Users/av/jupyter-env/lib/python3.13/site-packages (2.3.0)
Requirement already satisfied: numpy>=1.26.0 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/av/jupyter-env/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

## Creating Data

You can create a simple Series or DataFrame from a list or dictionary.

In [3]:
a_list =[10, 20, 30]

In [4]:
# Create a Series
my_series = pd.Series(a_list) #Built on top of NumPy arra
print(my_series)

0    10
1    20
2    30
dtype: int64

In [5]:
# Create a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
# creating a series from numPy Array
import numpy as np
import pandas as pd

index = ['a','b','c']
arr = np.array([100,200,300])

pd.Series(data=arr,index=index)

## Index in a Pandas Series

In a Pandas Series, each value has a corresponding index kind of like a label.

You can use these index labels (or numbers) to quickly look up values. Think of a Series like a dictionary: index → value.

In [6]:
import pandas as pd

# Create two Series representing fruit prices in different stores
store_a = pd.Series([0.99, 1.29, 2.49], index=['Apple', 'Banana', 'Mango'])
store_b = pd.Series([1.09, 1.19, 2.79], index=['Apple', 'Banana', 'Orange'])

In [7]:
print(store_a)

Apple     0.99
Banana    1.29
Mango     2.49
dtype: float64

In [8]:
print(store_a['Mango'])

2.49

A pandas series is usually homogenous (meaning all the same data types), its 1 dimensional , is similar to a excel spreadsheet column

## DataFrame Basics

What is a DataFrame?
A DataFrame is a 2D table (like an Excel sheet) with labeled rows and columns. It can hold different data types like numbers, text, or booleans.

Rows = individual records
Columns = variables/features
Comes from the pandas library
Each DataFrame has:

Data
Index (row labels)
Columns (column labels)

## Reading Data

Pandas can read various file types like CSV, Excel, JSON, etc.

In [45]:
# Read CSV file
df = pd.read_csv('dummy data/pandas_dummy_data.csv')

In [41]:
df

    ID       Name   Age         City  Score
0    1   Person_1  58.0      Houston  89.18
1    2   Person_2  48.0  Los Angeles  85.50
2    3   Person_3  34.0      Houston  95.49
3    4   Person_4  27.0  Los Angeles  78.89
4    5   Person_5  40.0  Los Angeles  64.78
5    6   Person_6  58.0      Houston    NaN
6    7   Person_7  38.0        Miami  90.43
7    8   Person_8  42.0  Los Angeles  82.45
8    9   Person_9  30.0  Los Angeles  90.84
9   10  Person_10  30.0      Houston  79.75
10  11  Person_11  43.0          NaN  80.91
11  12  Person_12  55.0  Los Angeles  77.10
12  13  Person_13  59.0      Houston  61.02
13  14  Person_14  43.0      Houston  64.32
14  15  Person_15  22.0     New York  61.26
15  16  Person_16   NaN        Miami  85.46
16  17  Person_17  21.0        Miami  72.57
17  18  Person_18  43.0  Los Angeles  80.34
18  19  Person_19  49.0        Miami  96.30
19  20  Person_20  57.0  Los Angeles  69.97
20  21        NaN  21.0     New York  76.42
21  22  Person_22  40.0      Houston  90.22
22  23  Person_23  52.0      Houston  69.15
23  24  Person_24  31.0      Houston  63.08
24  25  Person_25  41.0        Miami  71.59
25  26  Person_26  44.0     New York  66.45
26  27  Person_27  46.0        Miami  97.19
27  28  Person_28  47.0        Miami  92.32
28  29  Person_29  35.0     New York  85.34
29  30  Person_30  34.0     New York  94.86
30  31  Person_31  22.0     New York  92.15
31  32  Person_32  56.0     New York  67.46
32  33  Person_33  26.0      Houston  95.70
33  34  Person_34  40.0      Chicago  81.57
34  35  Person_35  28.0      Chicago  92.30
35  36  Person_36  58.0     New York  95.84
36  37  Person_37  37.0      Chicago  72.72
37  38  Person_38  23.0      Chicago  64.40
38  39  Person_39  44.0     New York  69.12
39  40  Person_40  33.0      Chicago  77.08
40  41  Person_41  28.0        Miami  92.72
41  42  Person_42  45.0  Los Angeles  94.43
42  43  Person_43  21.0  Los Angeles  60.28
43  44  Person_44  39.0     New York  80.43
44  45  Person_45  47.0      Houston  76.70
45  46  Person_46  26.0     New York  68.88
46  47  Person_47  27.0      Houston  64.79
47  48  Person_48  54.0  Los Angeles  73.50
48  49  Person_49  33.0     New York  97.72
49  50  Person_50  36.0        Miami  72.93

In [35]:
df.count()

ID       50
Name     49
Age      49
City     49
Score    49
dtype: int64

## Data Exploration

In [12]:
df.head()     # First 5 rows

   ID      Name   Age         City  Score
0   1  Person_1  58.0      Houston  89.18
1   2  Person_2  48.0  Los Angeles  85.50
2   3  Person_3  34.0      Houston  95.49
3   4  Person_4  27.0  Los Angeles  78.89
4   5  Person_5  40.0  Los Angeles  64.78

In [13]:
df.tail()     # Last 5 rows

    ID       Name   Age         City  Score
45  46  Person_46  26.0     New York  68.88
46  47  Person_47  27.0      Houston  64.79
47  48  Person_48  54.0  Los Angeles  73.50
48  49  Person_49  33.0     New York  97.72
49  50  Person_50  36.0        Miami  72.93

In [14]:
df.shape      # Rows and columns

(50, 5)

In [15]:
df.info()     # Summary info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      50 non-null     int64
 1   Name    49 non-null     object
 2   Age     49 non-null     float64
 3   City    49 non-null     object
 4   Score   49 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.1+ KB

In [16]:
df.describe() # Stats summary

             ID        Age      Score
count  50.00000  49.000000  49.000000
mean   25.50000  39.000000  79.671429
std    14.57738  11.461893  11.739419
min     1.00000  21.000000  60.280000
25%    13.25000  30.000000  69.150000
50%    25.50000  40.000000  79.750000
75%    37.75000  47.000000  90.840000
max    50.00000  59.000000  97.720000

## Selecting Data

In [17]:
# Select column
df['Name']

0      Person_1
1      Person_2
2      Person_3
3      Person_4
4      Person_5
5      Person_6
6      Person_7
7      Person_8
8      Person_9
9     Person_10
10    Person_11
11    Person_12
12    Person_13
13    Person_14
14    Person_15
15    Person_16
16    Person_17
17    Person_18
18    Person_19
19    Person_20
20          NaN
21    Person_22
22    Person_23
23    Person_24
24    Person_25
25    Person_26
26    Person_27
27    Person_28
28    Person_29
29    Person_30
30    Person_31
31    Person_32
32    Person_33
33    Person_34
34    Person_35
35    Person_36
36    Person_37
37    Person_38
38    Person_39
39    Person_40
40    Person_41
41    Person_42
42    Person_43
43    Person_44
44    Person_45
45    Person_46
46    Person_47
47    Person_48
48    Person_49
49    Person_50
Name: Name, dtype: object

In [20]:
# Select row by index
df.iloc[0]

ID              1
Name     Person_1
Age          58.0
City      Houston
Score       89.18
Name: 0, dtype: object

In [ ]:
# Select row by label (if index is labeled)
df.loc[0]

## Filtering Data

In [21]:
df[df['Age'] > 25]

    ID       Name   Age         City  Score
0    1   Person_1  58.0      Houston  89.18
1    2   Person_2  48.0  Los Angeles  85.50
2    3   Person_3  34.0      Houston  95.49
3    4   Person_4  27.0  Los Angeles  78.89
4    5   Person_5  40.0  Los Angeles  64.78
5    6   Person_6  58.0      Houston    NaN
6    7   Person_7  38.0        Miami  90.43
7    8   Person_8  42.0  Los Angeles  82.45
8    9   Person_9  30.0  Los Angeles  90.84
9   10  Person_10  30.0      Houston  79.75
10  11  Person_11  43.0          NaN  80.91
11  12  Person_12  55.0  Los Angeles  77.10
12  13  Person_13  59.0      Houston  61.02
13  14  Person_14  43.0      Houston  64.32
17  18  Person_18  43.0  Los Angeles  80.34
18  19  Person_19  49.0        Miami  96.30
19  20  Person_20  57.0  Los Angeles  69.97
21  22  Person_22  40.0      Houston  90.22
22  23  Person_23  52.0      Houston  69.15
23  24  Person_24  31.0      Houston  63.08
24  25  Person_25  41.0        Miami  71.59
25  26  Person_26  44.0     New York  66.45
26  27  Person_27  46.0        Miami  97.19
27  28  Person_28  47.0        Miami  92.32
28  29  Person_29  35.0     New York  85.34
29  30  Person_30  34.0     New York  94.86
31  32  Person_32  56.0     New York  67.46
32  33  Person_33  26.0      Houston  95.70
33  34  Person_34  40.0      Chicago  81.57
34  35  Person_35  28.0      Chicago  92.30
35  36  Person_36  58.0     New York  95.84
36  37  Person_37  37.0      Chicago  72.72
38  39  Person_39  44.0     New York  69.12
39  40  Person_40  33.0      Chicago  77.08
40  41  Person_41  28.0        Miami  92.72
41  42  Person_42  45.0  Los Angeles  94.43
43  44  Person_44  39.0     New York  80.43
44  45  Person_45  47.0      Houston  76.70
45  46  Person_46  26.0     New York  68.88
46  47  Person_47  27.0      Houston  64.79
47  48  Person_48  54.0  Los Angeles  73.50
48  49  Person_49  33.0     New York  97.72
49  50  Person_50  36.0        Miami  72.93

In [ ]:
1. df['Age'] grabs just the column --> evaluates every row one by one --> creates a boolean dataframe --> outer big dataframe gives back data where true

## Modifying Data

In [22]:
df['Age'] + 1

0     59.0
1     49.0
2     35.0
3     28.0
4     41.0
5     59.0
6     39.0
7     43.0
8     31.0
9     31.0
10    44.0
11    56.0
12    60.0
13    44.0
14    23.0
15     NaN
16    22.0
17    44.0
18    50.0
19    58.0
20    22.0
21    41.0
22    53.0
23    32.0
24    42.0
25    45.0
26    47.0
27    48.0
28    36.0
29    35.0
30    23.0
31    57.0
32    27.0
33    41.0
34    29.0
35    59.0
36    38.0
37    24.0
38    45.0
39    34.0
40    29.0
41    46.0
42    22.0
43    40.0
44    48.0
45    27.0
46    28.0
47    55.0
48    34.0
49    37.0
Name: Age, dtype: float64

In [23]:
df['Age']

0     58.0
1     48.0
2     34.0
3     27.0
4     40.0
5     58.0
6     38.0
7     42.0
8     30.0
9     30.0
10    43.0
11    55.0
12    59.0
13    43.0
14    22.0
15     NaN
16    21.0
17    43.0
18    49.0
19    57.0
20    21.0
21    40.0
22    52.0
23    31.0
24    41.0
25    44.0
26    46.0
27    47.0
28    35.0
29    34.0
30    22.0
31    56.0
32    26.0
33    40.0
34    28.0
35    58.0
36    37.0
37    23.0
38    44.0
39    33.0
40    28.0
41    45.0
42    21.0
43    39.0
44    47.0
45    26.0
46    27.0
47    54.0
48    33.0
49    36.0
Name: Age, dtype: float64

In [24]:
df['Age'] = df['Age'] + 1  # Add 1 to each age

In [25]:
df['Age']

0     59.0
1     49.0
2     35.0
3     28.0
4     41.0
5     59.0
6     39.0
7     43.0
8     31.0
9     31.0
10    44.0
11    56.0
12    60.0
13    44.0
14    23.0
15     NaN
16    22.0
17    44.0
18    50.0
19    58.0
20    22.0
21    41.0
22    53.0
23    32.0
24    42.0
25    45.0
26    47.0
27    48.0
28    36.0
29    35.0
30    23.0
31    57.0
32    27.0
33    41.0
34    29.0
35    59.0
36    38.0
37    24.0
38    45.0
39    34.0
40    29.0
41    46.0
42    22.0
43    40.0
44    48.0
45    27.0
46    28.0
47    55.0
48    34.0
49    37.0
Name: Age, dtype: float64

## Adding New Column

In [26]:
df.head()

   ID      Name   Age         City  Score
0   1  Person_1  59.0      Houston  89.18
1   2  Person_2  49.0  Los Angeles  85.50
2   3  Person_3  35.0      Houston  95.49
3   4  Person_4  28.0  Los Angeles  78.89
4   5  Person_5  41.0  Los Angeles  64.78

In [ ]:
df['Country'] = ['USA', 'UK', 'USA', 'UK', ...50 values]  # Must be same length as df aka 50 rows

In [ ]:
newlist = [some values]
df['newcolumn'] = newlist

## Deleting Columns

In [32]:
df.drop('City', axis=1, inplace=True) #inplace means dont return a new dataframe and edit the dataframe right here, axis 1 means work along ythe columns

In [28]:
df.drop('Age', axis=1) # without it we need to assign it again

    ID       Name         City  Score
0    1   Person_1      Houston  89.18
1    2   Person_2  Los Angeles  85.50
2    3   Person_3      Houston  95.49
3    4   Person_4  Los Angeles  78.89
4    5   Person_5  Los Angeles  64.78
5    6   Person_6      Houston    NaN
6    7   Person_7        Miami  90.43
7    8   Person_8  Los Angeles  82.45
8    9   Person_9  Los Angeles  90.84
9   10  Person_10      Houston  79.75
10  11  Person_11          NaN  80.91
11  12  Person_12  Los Angeles  77.10
12  13  Person_13      Houston  61.02
13  14  Person_14      Houston  64.32
14  15  Person_15     New York  61.26
15  16  Person_16        Miami  85.46
16  17  Person_17        Miami  72.57
17  18  Person_18  Los Angeles  80.34
18  19  Person_19        Miami  96.30
19  20  Person_20  Los Angeles  69.97
20  21        NaN     New York  76.42
21  22  Person_22      Houston  90.22
22  23  Person_23      Houston  69.15
23  24  Person_24      Houston  63.08
24  25  Person_25        Miami  71.59
25  26  Person_26     New York  66.45
26  27  Person_27        Miami  97.19
27  28  Person_28        Miami  92.32
28  29  Person_29     New York  85.34
29  30  Person_30     New York  94.86
30  31  Person_31     New York  92.15
31  32  Person_32     New York  67.46
32  33  Person_33      Houston  95.70
33  34  Person_34      Chicago  81.57
34  35  Person_35      Chicago  92.30
35  36  Person_36     New York  95.84
36  37  Person_37      Chicago  72.72
37  38  Person_38      Chicago  64.40
38  39  Person_39     New York  69.12
39  40  Person_40      Chicago  77.08
40  41  Person_41        Miami  92.72
41  42  Person_42  Los Angeles  94.43
42  43  Person_43  Los Angeles  60.28
43  44  Person_44     New York  80.43
44  45  Person_45      Houston  76.70
45  46  Person_46     New York  68.88
46  47  Person_47      Houston  64.79
47  48  Person_48  Los Angeles  73.50
48  49  Person_49     New York  97.72
49  50  Person_50        Miami  72.93

In [30]:
df = df.drop('Age', axis=1)

In [33]:
df.head()

   ID      Name  Score
0   1  Person_1  89.18
1   2  Person_2  85.50
2   3  Person_3  95.49
3   4  Person_4  78.89
4   5  Person_5  64.78

## Handling Missing Data

In [38]:
df = df.dropna()       # Remove missing rows

In [42]:
df.count()

ID       50
Name     49
Age      49
City     49
Score    49
dtype: int64

In [43]:
df = df.fillna(0)      # Replace missing with 0

In [44]:
df

    ID       Name   Age         City  Score
0    1   Person_1  58.0      Houston  89.18
1    2   Person_2  48.0  Los Angeles  85.50
2    3   Person_3  34.0      Houston  95.49
3    4   Person_4  27.0  Los Angeles  78.89
4    5   Person_5  40.0  Los Angeles  64.78
5    6   Person_6  58.0      Houston   0.00
6    7   Person_7  38.0        Miami  90.43
7    8   Person_8  42.0  Los Angeles  82.45
8    9   Person_9  30.0  Los Angeles  90.84
9   10  Person_10  30.0      Houston  79.75
10  11  Person_11  43.0            0  80.91
11  12  Person_12  55.0  Los Angeles  77.10
12  13  Person_13  59.0      Houston  61.02
13  14  Person_14  43.0      Houston  64.32
14  15  Person_15  22.0     New York  61.26
15  16  Person_16   0.0        Miami  85.46
16  17  Person_17  21.0        Miami  72.57
17  18  Person_18  43.0  Los Angeles  80.34
18  19  Person_19  49.0        Miami  96.30
19  20  Person_20  57.0  Los Angeles  69.97
20  21          0  21.0     New York  76.42
21  22  Person_22  40.0      Houston  90.22
22  23  Person_23  52.0      Houston  69.15
23  24  Person_24  31.0      Houston  63.08
24  25  Person_25  41.0        Miami  71.59
25  26  Person_26  44.0     New York  66.45
26  27  Person_27  46.0        Miami  97.19
27  28  Person_28  47.0        Miami  92.32
28  29  Person_29  35.0     New York  85.34
29  30  Person_30  34.0     New York  94.86
30  31  Person_31  22.0     New York  92.15
31  32  Person_32  56.0     New York  67.46
32  33  Person_33  26.0      Houston  95.70
33  34  Person_34  40.0      Chicago  81.57
34  35  Person_35  28.0      Chicago  92.30
35  36  Person_36  58.0     New York  95.84
36  37  Person_37  37.0      Chicago  72.72
37  38  Person_38  23.0      Chicago  64.40
38  39  Person_39  44.0     New York  69.12
39  40  Person_40  33.0      Chicago  77.08
40  41  Person_41  28.0        Miami  92.72
41  42  Person_42  45.0  Los Angeles  94.43
42  43  Person_43  21.0  Los Angeles  60.28
43  44  Person_44  39.0     New York  80.43
44  45  Person_45  47.0      Houston  76.70
45  46  Person_46  26.0     New York  68.88
46  47  Person_47  27.0      Houston  64.79
47  48  Person_48  54.0  Los Angeles  73.50
48  49  Person_49  33.0     New York  97.72
49  50  Person_50  36.0        Miami  72.93

In [46]:
#notice row 20!
df = df.dropna().reset_index(drop=True) #remove nulls,reset the index, remove old index column

In [47]:
df

    ID       Name   Age         City  Score
0    1   Person_1  58.0      Houston  89.18
1    2   Person_2  48.0  Los Angeles  85.50
2    3   Person_3  34.0      Houston  95.49
3    4   Person_4  27.0  Los Angeles  78.89
4    5   Person_5  40.0  Los Angeles  64.78
5    7   Person_7  38.0        Miami  90.43
6    8   Person_8  42.0  Los Angeles  82.45
7    9   Person_9  30.0  Los Angeles  90.84
8   10  Person_10  30.0      Houston  79.75
9   12  Person_12  55.0  Los Angeles  77.10
10  13  Person_13  59.0      Houston  61.02
11  14  Person_14  43.0      Houston  64.32
12  15  Person_15  22.0     New York  61.26
13  17  Person_17  21.0        Miami  72.57
14  18  Person_18  43.0  Los Angeles  80.34
15  19  Person_19  49.0        Miami  96.30
16  20  Person_20  57.0  Los Angeles  69.97
17  22  Person_22  40.0      Houston  90.22
18  23  Person_23  52.0      Houston  69.15
19  24  Person_24  31.0      Houston  63.08
20  25  Person_25  41.0        Miami  71.59
21  26  Person_26  44.0     New York  66.45
22  27  Person_27  46.0        Miami  97.19
23  28  Person_28  47.0        Miami  92.32
24  29  Person_29  35.0     New York  85.34
25  30  Person_30  34.0     New York  94.86
26  31  Person_31  22.0     New York  92.15
27  32  Person_32  56.0     New York  67.46
28  33  Person_33  26.0      Houston  95.70
29  34  Person_34  40.0      Chicago  81.57
30  35  Person_35  28.0      Chicago  92.30
31  36  Person_36  58.0     New York  95.84
32  37  Person_37  37.0      Chicago  72.72
33  38  Person_38  23.0      Chicago  64.40
34  39  Person_39  44.0     New York  69.12
35  40  Person_40  33.0      Chicago  77.08
36  41  Person_41  28.0        Miami  92.72
37  42  Person_42  45.0  Los Angeles  94.43
38  43  Person_43  21.0  Los Angeles  60.28
39  44  Person_44  39.0     New York  80.43
40  45  Person_45  47.0      Houston  76.70
41  46  Person_46  26.0     New York  68.88
42  47  Person_47  27.0      Houston  64.79
43  48  Person_48  54.0  Los Angeles  73.50
44  49  Person_49  33.0     New York  97.72
45  50  Person_50  36.0        Miami  72.93

## Grouping and Aggregation

In [48]:
#df.groupby('ColumnName').agg_function()
df.groupby('City')['Age'].mean()

City
Chicago        32.200000
Houston        40.636364
Los Angeles    42.000000
Miami          38.250000
New York       37.545455
Name: Age, dtype: float64

## Sorting

In [49]:
df.sort_values(by='Age')

    ID       Name   Age         City  Score
13  17  Person_17  21.0        Miami  72.57
38  43  Person_43  21.0  Los Angeles  60.28
26  31  Person_31  22.0     New York  92.15
12  15  Person_15  22.0     New York  61.26
33  38  Person_38  23.0      Chicago  64.40
41  46  Person_46  26.0     New York  68.88
28  33  Person_33  26.0      Houston  95.70
3    4   Person_4  27.0  Los Angeles  78.89
42  47  Person_47  27.0      Houston  64.79
30  35  Person_35  28.0      Chicago  92.30
36  41  Person_41  28.0        Miami  92.72
8   10  Person_10  30.0      Houston  79.75
7    9   Person_9  30.0  Los Angeles  90.84
19  24  Person_24  31.0      Houston  63.08
44  49  Person_49  33.0     New York  97.72
35  40  Person_40  33.0      Chicago  77.08
25  30  Person_30  34.0     New York  94.86
2    3   Person_3  34.0      Houston  95.49
24  29  Person_29  35.0     New York  85.34
45  50  Person_50  36.0        Miami  72.93
32  37  Person_37  37.0      Chicago  72.72
5    7   Person_7  38.0        Miami  90.43
39  44  Person_44  39.0     New York  80.43
29  34  Person_34  40.0      Chicago  81.57
17  22  Person_22  40.0      Houston  90.22
4    5   Person_5  40.0  Los Angeles  64.78
20  25  Person_25  41.0        Miami  71.59
6    8   Person_8  42.0  Los Angeles  82.45
11  14  Person_14  43.0      Houston  64.32
14  18  Person_18  43.0  Los Angeles  80.34
21  26  Person_26  44.0     New York  66.45
34  39  Person_39  44.0     New York  69.12
37  42  Person_42  45.0  Los Angeles  94.43
22  27  Person_27  46.0        Miami  97.19
40  45  Person_45  47.0      Houston  76.70
23  28  Person_28  47.0        Miami  92.32
1    2   Person_2  48.0  Los Angeles  85.50
15  19  Person_19  49.0        Miami  96.30
18  23  Person_23  52.0      Houston  69.15
43  48  Person_48  54.0  Los Angeles  73.50
9   12  Person_12  55.0  Los Angeles  77.10
27  32  Person_32  56.0     New York  67.46
16  20  Person_20  57.0  Los Angeles  69.97
0    1   Person_1  58.0      Houston  89.18
31  36  Person_36  58.0     New York  95.84
10  13  Person_13  59.0      Houston  61.02

## Exporting Data

In [50]:
df.to_csv('dummy data/output.csv', index=False)