## In this mini project we will see how Python is used to work with a real world dataset

Installs the pandas library, which is essential for data manipulation in Python

pip install pandas

Imports the pandas library and assigns it the alias pd so you can reference it easily

In [39]:
import pandas as pd

Loads the CSV file called student_data.csv into a DataFrame called df. This is your main dataset you'll analyze.

In [40]:
df = pd.read_csv("Data/student_data.csv")

Displays the first 5 rows of the dataset. This helps preview the structure of the data, column names, and some sample values.

In [41]:
df.head()

,Enrollment ID,Course Name,Category,Student Name,Age,Country,Enrollment Date,Completion Status,Course Rating,Email,Grade
0,1001,SQL Mastery,Data,Megan,50,UK,2025-01-17,Completed,4.0,greenwilliam@yahoo.com,Student is a freshman
1,1002,Web Dev,Data,Lauren,31,Canada,2025-05-15,In Progress,4.0,corey15@castro-gomez.com,Student is a junior
2,1003,Web Dev,Data,Kristen,34,Canada,2024-10-06,Completed,5.0,vclayton@cross.com,Student is a sophomore
3,1004,AI for Beginners,Cloud,Victoria,37,India,2025-04-18,Dropped,3.2,turnerkelly@gmail.com,Student is a junior
4,1005,Python Basics,Cloud,Ivan,24,Germany,2025-03-08,In Progress,3.7,salazardiane@jones-shelton.com,Student is a freshman

Counts non-null (non-empty) values in each column. Useful for checking missing data.

In [42]:
df.count()

Enrollment ID        50
Course Name          50
Category             50
Student Name         50
Age                  50
Country              50
Enrollment Date      50
Completion Status    50
Course Rating        50
Email                50
Grade                50
dtype: int64

This converts the count of non-null values in the 'Student Name' column to a plain Python int

In [12]:
int(df['Student Name'].count())

50

This returns the maximum value in the 'Course Rating' column

In [14]:
df['Course Rating'].max()  #int(df['Mrp'].max())

np.float64(5.0)

In [15]:
int(df['Course Rating'].min())

3

This filters the DataFrame to show only rows where the course rating is exactly 5

In [16]:
df[df['Course Rating']==5]

,Enrollment ID,Course Name,Category,Student Name,Age,Country,Enrollment Date,Completion Status,Course Rating,Email,Grade
2,1003,Web Dev,Data,Kristen,34,Canada,2024-10-06,Completed,5.0,vclayton@cross.com,Student is a sophomore

In [18]:
df[df['Course Rating']==3]

,Enrollment ID,Course Name,Category,Student Name,Age,Country,Enrollment Date,Completion Status,Course Rating,Email,Grade
32,1033,Python Basics,AI,Beverly,29,Australia,2023-10-08,In Progress,3.0,sonyabrock@yahoo.com,Student is a freshman
46,1047,Cloud Computing,Data,Robert,31,USA,2024-06-26,In Progress,3.0,fwilson@gmail.com,Student is a junior
49,1050,Data Science,Programming,John,23,Germany,2024-01-16,In Progress,3.0,htrevino@brewer-wilson.org,Student is a junior

In [19]:
df[df['Age']>=50]

,Enrollment ID,Course Name,Category,Student Name,Age,Country,Enrollment Date,Completion Status,Course Rating,Email,Grade
0,1001,SQL Mastery,Data,Megan,50,UK,2025-01-17,Completed,4.0,greenwilliam@yahoo.com,Student is a freshman

Converts the first entry in the 'Grade' column to uppercase

In [20]:
list(df['Grade'])[0].upper()

'STUDENT IS A FRESHMAN'

In [21]:
list(df['Grade'])[0].lower()

'student is a freshman'

Retrieves the third value in the 'Grade' column

In [27]:
list(df['Grade'])[2]

'Student is a sophomore'

Takes the 3rd value in 'Grade'
Slices characters from index 13 to 40
Converts the result to uppercase
Strips any whitespace from the ends

In [32]:
list(df['Grade'])[2][13:40].upper().strip()

'SOPHOMORE'

Creates a new column 'Students College Year' by slicing characters 13 to 40 from each 'Grade' string.

⚠️ This can break if string formats vary — use .str.split().str[-1] instead for flexibility.

In [33]:
df['Students College Year'] = df['Grade'].str[13:40]

In [34]:
df.head()

,Enrollment ID,Course Name,Category,Student Name,Age,Country,Enrollment Date,Completion Status,Course Rating,Email,Grade,Students College Year
0,1001,SQL Mastery,Data,Megan,50,UK,2025-01-17,Completed,4.0,greenwilliam@yahoo.com,Student is a freshman,freshman
1,1002,Web Dev,Data,Lauren,31,Canada,2025-05-15,In Progress,4.0,corey15@castro-gomez.com,Student is a junior,junior
2,1003,Web Dev,Data,Kristen,34,Canada,2024-10-06,Completed,5.0,vclayton@cross.com,Student is a sophomore,sophomore
3,1004,AI for Beginners,Cloud,Victoria,37,India,2025-04-18,Dropped,3.2,turnerkelly@gmail.com,Student is a junior,junior
4,1005,Python Basics,Cloud,Ivan,24,Germany,2025-03-08,In Progress,3.7,salazardiane@jones-shelton.com,Student is a freshman,freshman

.str.split() → splits the string into a list of words
.str[-1] → grabs the last word (e.g., 'freshman', 'senior')
Assigns the result to a new column Grade Level

In [36]:
df['Students College Year']  = df['Grade Level'] = df['Grade'].str.split().str[-1]

 Sorts the DataFrame by 'Course Rating' in descending order (from highest to lowest).

In [43]:
df.sort_values(by=['Course Rating'], ascending = False)

,Enrollment ID,Course Name,Category,Student Name,Age,Country,Enrollment Date,Completion Status,Course Rating,Email,Grade
2,1003,Web Dev,Data,Kristen,34,Canada,2024-10-06,Completed,5.0,vclayton@cross.com,Student is a sophomore
11,1012,Cloud Computing,Programming,Matthew,31,UK,2023-12-11,Dropped,4.9,rgray@baxter.org,Student is a junior
30,1031,SQL Mastery,AI,Michael,31,Australia,2023-06-16,Completed,4.9,chad23@harris.com,Student is a freshman
29,1030,Cloud Computing,Data,Patricia,40,UK,2024-05-01,Completed,4.8,perrycory@navarro.info,Student is a junior
15,1016,Python Basics,Cloud,Ashley,20,India,2025-03-29,Completed,4.7,djoseph@graham.biz,Student is a senior
19,1020,AI for Beginners,Programming,Michael,39,Canada,2023-07-28,In Progress,4.7,mgoodwin@crawford.com,Student is a sophomore
40,1041,Cloud Computing,AI,Danielle,43,USA,2024-01-22,In Progress,4.7,karenroberts@hamilton.com,Student is a sophomore
25,1026,Data Science,Cloud,Pamela,31,Germany,2024-09-18,Completed,4.5,lisagomez@carr.info,Student is a sophomore
20,1021,Data Science,Programming,Michael,25,UK,2025-03-12,Dropped,4.4,hintontonya@elliott.biz,Student is a sophomore
38,1039,SQL Mastery,Cloud,David,30,USA,2024-04-15,Completed,4.4,anitaevans@hotmail.com,Student is a junior
48,1049,AI for Beginners,Cloud,Chelsea,35,UK,2025-02-10,Completed,4.4,kimberly89@herrera-green.com,Student is a freshman
33,1034,Cloud Computing,Data,Andrea,37,Canada,2025-01-04,Dropped,4.3,wevans@wright.com,Student is a freshman
17,1018,Data Science,Data,Kevin,44,Canada,2023-09-01,Dropped,4.2,zwells@martinez-wilson.info,Student is a senior
7,1008,SQL Mastery,Cloud,Catherine,18,Australia,2024-08-29,Dropped,4.2,hdavis@jacobs.com,Student is a freshman
28,1029,Data Science,Programming,Stanley,20,Germany,2025-02-11,Dropped,4.2,wintersbill@santana-duffy.org,Student is a junior
26,1027,Python Basics,Cloud,Mario,45,Canada,2024-12-03,Completed,4.2,patrickfrank@yahoo.com,Student is a junior
36,1037,SQL Mastery,Development,Raymond,40,UK,2025-04-30,Dropped,4.2,qgarcia@yahoo.com,Student is a sophomore
10,1011,Web Dev,AI,Amy,37,USA,2023-09-21,In Progress,4.1,sbell@howard.org,Student is a sophomore
31,1032,Python Basics,Cloud,Donald,39,India,2024-05-26,Completed,4.1,qcooper@johnson.com,Student is a junior
42,1043,Python Basics,Development,Monica,46,India,2024-03-17,Dropped,4.1,jesseevans@bush.com,Student is a freshman
44,1045,Web Dev,Data,Charlotte,30,Germany,2024-08-15,Completed,4.1,mlee@obrien.com,Student is a sophomore
1,1002,Web Dev,Data,Lauren,31,Canada,2025-05-15,In Progress,4.0,corey15@castro-gomez.com,Student is a junior
14,1015,Data Science,Programming,Andrew,34,Australia,2025-05-18,Dropped,4.0,callahandennis@hotmail.com,Student is a freshman
16,1017,Cloud Computing,AI,Brandy,35,Germany,2024-03-15,Dropped,4.0,kellywoods@gmail.com,Student is a senior
0,1001,SQL Mastery,Data,Megan,50,UK,2025-01-17,Completed,4.0,greenwilliam@yahoo.com,Student is a freshman
43,1044,SQL Mastery,AI,Shawn,20,USA,2023-12-23,Dropped,4.0,matthewwilliams@gmail.com,Student is a senior
34,1035,SQL Mastery,Cloud,Joshua,18,India,2024-08-15,In Progress,3.9,lhebert@reynolds-wright.info,Student is a junior
5,1006,Web Dev,AI,Janet,48,India,2024-01-09,Dropped,3.9,pattylawrence@riley-hayes.com,Student is a sophomore
37,1038,Cloud Computing,AI,David,37,Australia,2025-04-06,Completed,3.8,carloscallahan@meyer-berry.com,Student is a junior
45,1046,Cloud Computing,Programming,Mary,18,India,2023-12-21,Dropped,3.8,zachary64@yahoo.com,Student is a freshman
23,1024,Cloud Computing,Data,Julie,25,Canada,2025-05-12,Dropped,3.8,amanda96@bruce-compton.org,Student is a freshman
39,1040,Data Science,Data,Paige,46,Australia,2023-11-23,Completed,3.8,thomas08@mcdaniel.biz,Student is a senior
4,1005,Python Basics,Cloud,Ivan,24,Germany,2025-03-08,In Progress,3.7,salazardiane@jones-shelton.com,Student is a freshman
27,1028,Web Dev,Programming,David,37,USA,2024-11-20,Completed,3.7,susanhughes@yahoo.com,Student is a junior
8,1009,Web Dev,Data,Mary,22,UK,2023-08-02,Dropped,3.4,lucasmichael@brown.com,Student is a freshman
13,1014,SQL Mastery,Development,Stefanie,36,India,2024-04-28,Dropped,3.4,lewisjennifer@gmail.com,Student is a junior
24,1025,Web Dev,Programming,Mallory,19,Canada,2025-01-29,Completed,3.4,dpatrick@gmail.com,Student is a sophomore
47,1048,Python Basics,Cloud,Lisa,24,Canada,2024-08-16,Dropped,3.4,haleyjohn@gmail.com,Student is a sophomore
41,1042,AI for Beginners,Data,Renee,20,Australia,2024-05-18,Dropped,3.3,fsimmons@yahoo.com,Student is a junior
35,1036,Python Basics,Development,Christine,35,USA,2023-06-15,Dropped,3.3,danny48@moore.info,Student is a sophomore
6,1007,AI for Beginners,Development,Allen,18,Canada,2024-01-05,Completed,3.2,nathanjackson@cabrera-garcia.com,Student is a junior
9,1010,AI for Beginners,Data,Brian,46,India,2024-11-15,Completed,3.2,matthewking@morse.biz,Student is a freshman
12,1013,AI for Beginners,AI,Aaron,46,UK,2023-07-09,Dropped,3.2,larry70@yahoo.com,Student is a junior
3,1004,AI for Beginners,Cloud,Victoria,37,India,2025-04-18,Dropped,3.2,turnerkelly@gmail.com,Student is a junior
21,1022,Web Dev,Data,Sydney,21,Germany,2025-05-07,In Progress,3.2,austin24@hotmail.com,Student is a senior
18,1019,SQL Mastery,Data,Lindsey,40,Australia,2023-11-09,Dropped,3.2,cruzcorey@stone.org,Student is a junior
22,1023,Data Science,Cloud,Misty,22,USA,2023-07-09,Completed,3.1,davidturner@rivera-martin.com,Student is a junior
32,1033,Python Basics,AI,Beverly,29,Australia,2023-10-08,In Progress,3.0,sonyabrock@yahoo.com,Student is a freshman
46,1047,Cloud Computing,Data,Robert,31,USA,2024-06-26,In Progress,3.0,fwilson@gmail.com,Student is a junior
49,1050,Data Science,Programming,John,23,Germany,2024-01-16,In Progress,3.0,htrevino@brewer-wilson.org,Student is a junior